/**
 * 6p continent schematic — mirrors `tools/v2/mapgen.py` (HTML/SVG coords only).
 */
import type { RegionId } from "@rr/engine2";

export const CONTINENT_6P_REGION_LAYOUT: Record<RegionId, readonly [number, number]> = {
  r_core_foxfire_ruins: [382, 259],
  r_core_three_trails_market: [618, 259],
  r_core_moon_ford: [500, 427],
  r_border_snowpine_reach: [702, 91],
  r_border_glasswood_verge: [870, 360],
  r_border_saltfen_crossing: [702, 629],
  r_border_hillmire_gate: [298, 629],
  r_border_howling_pass: [130, 360],
  r_border_frostpass: [298, 91],
  r_arc_frosthold: [500, -178],
  r_arc_ice_shelf: [399, -77],
  r_arc_white_wastes: [601, -77],
  r_tri_hidden_grove: [1071, -144],
  r_tri_tricky_woods: [1004, -43],
  r_tri_whisper_thicket: [1138, -43],
  r_red_mirage_camp: [1071, 864],
  r_red_vast_dunes: [1004, 763],
  r_red_rare_veins: [1138, 763],
  r_br_root_cities: [500, 898],
  r_br_reeky_canopy: [399, 797],
  r_br_mire_channels: [601, 797],
  r_or_vulpgard: [-71, 864],
  r_or_windy_plains: [-4, 763],
  r_or_rocky_hills: [-138, 763],
  r_gr_middle_high_mountains: [-71, -144],
  r_gr_upper_high_mountains: [-4, -43],
  r_gr_lower_high_mountains: [-138, -43],
};

/** Undirected trail edges for drawing lines (same as `_CONTINENT_6P_TRAILS`). */
export const CONTINENT_6P_TRAILS: readonly (readonly [RegionId, RegionId])[] = [
  ["r_arc_frosthold", "r_arc_ice_shelf"],
  ["r_arc_frosthold", "r_arc_white_wastes"],
  ["r_arc_ice_shelf", "r_arc_white_wastes"],
  ["r_tri_hidden_grove", "r_tri_tricky_woods"],
  ["r_tri_hidden_grove", "r_tri_whisper_thicket"],
  ["r_tri_tricky_woods", "r_tri_whisper_thicket"],
  ["r_red_mirage_camp", "r_red_vast_dunes"],
  ["r_red_mirage_camp", "r_red_rare_veins"],
  ["r_red_vast_dunes", "r_red_rare_veins"],
  ["r_br_root_cities", "r_br_reeky_canopy"],
  ["r_br_root_cities", "r_br_mire_channels"],
  ["r_br_reeky_canopy", "r_br_mire_channels"],
  ["r_or_vulpgard", "r_or_windy_plains"],
  ["r_or_vulpgard", "r_or_rocky_hills"],
  ["r_or_windy_plains", "r_or_rocky_hills"],
  ["r_gr_middle_high_mountains", "r_gr_upper_high_mountains"],
  ["r_gr_middle_high_mountains", "r_gr_lower_high_mountains"],
  ["r_gr_upper_high_mountains", "r_gr_lower_high_mountains"],
  ["r_arc_ice_shelf", "r_border_snowpine_reach"],
  ["r_tri_whisper_thicket", "r_border_snowpine_reach"],
  ["r_tri_tricky_woods", "r_border_glasswood_verge"],
  ["r_red_rare_veins", "r_border_glasswood_verge"],
  ["r_red_vast_dunes", "r_border_saltfen_crossing"],
  ["r_br_mire_channels", "r_border_saltfen_crossing"],
  ["r_br_reeky_canopy", "r_border_hillmire_gate"],
  ["r_or_rocky_hills", "r_border_hillmire_gate"],
  ["r_or_windy_plains", "r_border_howling_pass"],
  ["r_gr_lower_high_mountains", "r_border_howling_pass"],
  ["r_gr_upper_high_mountains", "r_border_frostpass"],
  ["r_arc_white_wastes", "r_border_frostpass"],
  ["r_arc_white_wastes", "r_core_foxfire_ruins"],
  ["r_red_rare_veins", "r_core_foxfire_ruins"],
  ["r_br_mire_channels", "r_core_foxfire_ruins"],
  ["r_gr_upper_high_mountains", "r_core_foxfire_ruins"],
  ["r_tri_tricky_woods", "r_core_three_trails_market"],
  ["r_red_vast_dunes", "r_core_three_trails_market"],
  ["r_or_rocky_hills", "r_core_three_trails_market"],
  ["r_gr_lower_high_mountains", "r_core_three_trails_market"],
  ["r_arc_ice_shelf", "r_core_moon_ford"],
  ["r_tri_whisper_thicket", "r_core_moon_ford"],
  ["r_br_reeky_canopy", "r_core_moon_ford"],
  ["r_or_windy_plains", "r_core_moon_ford"],
];
